export const salaryData = [
  {
    number: 1,
    salaryItem: "Коррекция длины волос",
    type: "% от услуг",
    revenue: {
      mainText: "3 400 ₸",
      subText: "по чеку",
    },
    materials: "0 ₸",
    salary: "+1 700 ₸",
    salaryFormula: "50% от 3 400 ₸",
    accrued: {
      mainText: "31 марта, 12:22",
      subText: "Автоматически",
    },
    link: "https://example.com/visit1",
    linkText: "Посещение № 773",
    employee: "Алена, ID 14",
    deleteLink: "https://example.com/delete1",
  },
  {
    number: 2,
    salaryItem: "Коррекция длины волос",
    type: "% от услуг",
    revenue: {
      mainText: "3 400 ₸",
      subText: "по чеку",
    },
    materials: "0 ₸",
    salary: "+1 700 ₸",
    salaryFormula: "50% от 3 400 ₸",
    accrued: {
      mainText: "31 марта, 12:22",
      subText: "Автоматически",
    },
    link: "https://example.com/visit2",
    linkText: "Посещение № 773",
    employee: "Алена, ID 14",
    deleteLink: "https://example.com/delete2",
  },
  {
    number: 3,
    salaryItem: "Коррекция длины волос",
    type: "% от услуг",
    revenue: {
      mainText: "3 400 ₸",
      subText: "по чеку",
    },
    materials: "0 ₸",
    salary: "+1 700 ₸",
    salaryFormula: "50% от 3 400 ₸",
    accrued: {
      mainText: "31 марта, 12:22",
      subText: "Автоматически",
    },
    link: "https://example.com/visit3",
    linkText: "Посещение № 773",
    employee: "Алена, ID 14",
    deleteLink: "https://example.com/delete3",
  },
  {
    number: 4,
    salaryItem: "Коррекция длины волос",
    type: "% от услуг",
    revenue: {
      mainText: "3 400 ₸",
      subText: "по чеку",
    },
    materials: "0 ₸",
    salary: "+1 700 ₸",
    salaryFormula: "50% от 3 400 ₸",
    accrued: {
      mainText: "31 марта, 12:22",
      subText: "Автоматически",
    },
    link: "https://example.com/visit4",
    linkText: "Посещение № 773",
    employee: "Алена, ID 14",
    deleteLink: "https://example.com/delete4",
  },
];
