import MaterialData from "../table-materials/table-materials";

export const costData = [
  {
    position: "Универсал",
    cost: 0,
    costFrom: 0,
    costTo: 0,
    shortHair: 0,
    mediumHair: 0,
    longHair: 0,
    roots: 0,
  },
  {
    position: "Стилист",
    cost: 0,
    costFrom: 0,
    costTo: 0,
    shortHair: 0,
    mediumHair: 0,
    longHair: 0,
    roots: 0,
  },
];

export const durationData = [
  {
    position: "Универсал",
    cost: 60,
    costFrom: 60,
    costTo: 60,
    shortHair: 60,
    mediumHair: 60,
    longHair: 60,
    roots: 60,
    children: [
      {
        position: "Имя Фамилия",
        cost: 60,
        costFrom: 60,
        costTo: 60,
        shortHair: 60,
        mediumHair: 60,
        longHair: 60,
        roots: 60,
      },
      {
        position: "Имя Фамилия",
        cost: 60,
        costFrom: 60,
        costTo: 60,
        shortHair: 60,
        mediumHair: 60,
        longHair: 60,
        roots: 60,
      },
    ],
  },
  {
    position: "Стилист",
    cost: 60,
    costFrom: 60,
    costTo: 60,
    shortHair: 60,
    mediumHair: 60,
    longHair: 60,
    roots: 60,
    children: [
      {
        position: "Имя Фамилия",
        cost: 60,
        costFrom: 60,
        costTo: 60,
        shortHair: 60,
        mediumHair: 60,
        longHair: 60,
        roots: 60,
      },
      {
        position: "Имя Фамилия",
        cost: 60,
        costFrom: 60,
        costTo: 60,
        shortHair: 60,
        mediumHair: 60,
        longHair: 60,
        roots: 60,
      },
    ],
  },
];

export const materialData = [
  {
    material: "Парикмахерский зал > Эстель > Эстель делюкс",
    cost: 20,
    costFrom: 0,
    costTo: 0,
    shortHair: 0,
    mediumHair: 0,
    longHair: 0,
    roots: 0,
    alwaysUse: true,
    canChange: false,
    paidByClient: false,
    finalCost: "1 мл = 200 руб.",
  },
  {
    material: "Парикмахерский зал > Эстель > Эстель делюкс",
    cost: 20,
    costFrom: 0,
    costTo: 0,
    shortHair: 0,
    mediumHair: 0,
    longHair: 0,
    roots: 0,
    alwaysUse: true,
    canChange: false,
    paidByClient: false,
    finalCost: "1 мл = 200 руб.",
  },
];
