export const tableHeaders = [
    { id: "number", label: "№" },
    { id: "article", label: "Артикул" },
    { id: "name", label: "Название" },
    { id: "limit", label: "Лимит" },
    { id: "storage", label: "Склад" },
    { id: "hall", label: "Зал" },
    { id: "display", label: "Витрина" },
    { id: "totalStorage", label: "Склад общий" },
    { id: "production", label: "Производство" },
    { id: "total", label: "Всего" },
    { id: "weeklyConsumption", label: "Неделя" },
    { id: "monthlyConsumption", label: "Месяц" },
    { id: "quarterlyConsumption", label: "Квартал" },
  ];
  
  export const tableData = [
    {
      number: 1,
      article: "99756522",
      name: "Estel шампунь",
      limit: "20",
      unit: "мл",
      storage: "1 шт.",
      hall: "-40 мл",
      display: "0 шт.",
      totalStorage: "-40 мл",
      production: "0 шт.",
      total: "20 мл",
      weeklyConsumption: "18 мл",
      monthlyConsumption: "18 мл",
      quarterlyConsumption: "18 мл",
    },
    {
      number: 2,
      article: "99756684",
      name: "Estel шампунь",
      limit: "20",
      unit: "мл",
      storage: "1 шт.",
      hall: "-40 мл",
      display: "0 шт.",
      totalStorage: "-40 мл",
      production: "0 шт.",
      total: "20 мл",
      weeklyConsumption: "18 мл",
      monthlyConsumption: "18 мл",
      quarterlyConsumption: "18 мл",
    },
  ];
  